# .pages.yml — Pages CMS configuration

# Media (equivalent to Decap's media/public_folder)
media:
  input: public/images/uploads     # folder inside your repo
  output: /images/uploads          # public URL your site uses

# Content types
content:
  - name: projects
    label: Projects
    type: collection
    path: src/data/projects        # where your .md files live
    format: yaml-frontmatter       # frontmatter + body content
    filename: "{name}.md"          # create files from the 'name' field
    view:                          # list view options in the UI
      fields: [name, title, category, kind, year]
      sort: [year, name]
      default:
        sort: year
        order: desc
    fields:
      - name: name
        label: Name
        type: string
        required: true

      - name: title
        label: Title
        type: string
        required: false

      # Images: array of { src, alt }
      - name: images
        label: Images
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{fields.alt} — {fields.src}"
        fields:
          - name: src
            label: Image
            type: image
          - name: alt
            label: Alt Text
            type: string

      - name: category
        label: Category
        type: select
        options: [A, B, C]
        default: B

      - name: kind
        label: Kind
        type: select
        options: [image, text, video]
        default: image

      - name: video
        label: Video URL
        type: string
        required: false

      - name: startTime
        label: Video Starttime
        type: number
        required: false

      - name: order_about
        label: Order About
        type: number
        required: false

      - name: order_projects
        label: Order Projects
        type: number
        required: false

      - name: order_video
        label: Order Video
        type: number
        required: false

      # Optional: add 'year' so you can sort by it in the UI
      - name: year
        label: Year
        type: number
        required: false

      # Body fields
      - name: body
        label: Body (DE)
        type: rich-text
        required: false

      - name: body_en
        label: Body (EN)
        type: rich-text
        required: false

# Optional global settings
settings:
  content:
    merge: true   # updates only submitted fields when editing existing files
