# .pages.yml — Pages CMS configuration

media:
  input: public/images/uploads
  output: /images/uploads

content:
  - name: projects
    label: Projects
    type: collection
    path: src/data/projects
    format: yaml-frontmatter
         # <- use field substitution with single braces
    view:
      primary: name               # <- ensures {primary} would be 'name' if you prefer
      fields: [name, online, title, category, kind, order_projects]
      sort: [category, order_projects]
      default:
        sort: year
        order: desc
    fields:
      - name: name
        label: Name
        type: string
        required: true

      - name: title
        label: Title
        type: string
        required: false
        # (Defaults are static strings; leave empty or fill manually.)

      - name: year
        label: Year
        type: number
        required: false

      # Images: repeatable object { src, alt }
      - name: images
        label: Images
        type: object
        list: true
        fields:
          - name: src
            label: Image
            type: image
          - name: alt
            label: Alt Text
            type: string

      - name: category
        label: Category
        type: select
        options:
          values: [A, B, C]
        default: B

      - name: kind
        label: Kind
        type: select
        options:
          values: [image, text, video]
        default: image

      - name: online
        label: Online
        type: boolean
        required: false
        default: true

      - name: video
        label: Video URL
        type: string
        required: false

      - name: startTime
        label: Video Starttime
        type: number
        required: false
        default: 0

      - name: order_about
        label: Order About
        type: number
        required: false
        default: 0

      - name: order_projects
        label: Order Projects
        type: number
        required: false
        default: 0

      - name: order_video
        label: Order Video
        type: number
        required: false
        default: 0

      - name: body
        label: Body (DE)
        type: rich-text
        required: false

      - name: body_en
        label: Body (EN)
        type: rich-text
        required: false