backend:
  name: github
  repo: meinrehlein/simone

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "projects"
    label: "Projects"
    label_singular: "Project"
    folder: "src/data/projects"
    create: true
    extension: "md"
    format: "frontmatter"
    slug: "{{name}}"
    sortable_fields: [commit_date, year, month]
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Year", name: "year", widget: "number" }
      - { label: "Month in numbers from '1' to '12'", name: "month", widget: "number", min: 1, max: 12 }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Type (DE) z.B. 'Bühnenbild'", name: "type", widget: "string" }
      - { label: "Type (EN) e.g. 'Stagedesign'", name: "type_en", widget: "string" }
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - { label: "Image", name: "src", widget: "image" }
          - { label: "Alt Text", name: "alt", widget: "string" }
      - { label: "Body (DE)", name: "body", widget: "markdown", required: false }
      - { label: "Body (EN)", name: "body_en", widget: "markdown", required: false }
