backend:
  name: github
  repo: meinrehlein/jrweb
  branch: main
  auth_type: implicit
  base_url: https://meinrehlein.netlify.app/.netlify/functions
  auth_endpoint: github-oauth
  site_domain: https://meinrehlein.netlify.app

media_folder: "public/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: projects
    label: Projects
    label_singular: Project
    folder: "src/data/projects"
    create: true
    extension: md
    slug: "{{name}}"
    sortable_fields: [commit_date, year]
    fields:
      - { label: Name, name: name, widget: string}
      - { label: Title, name: title, widget: string, required: false }
      - label: Images
        name: images
        widget: list
        fields:
          - { label: Image, name: src, widget: image }
          - { label: Alt Text, name: alt, widget: string }
      - { label: Category, name: category, widget: select, options: [A,B,C], default: B }
      - { label: Kind, name: kind, widget: select, options: [image,text,video], default: image }
      - { label: Video URL, name: video, widget: string, required: false }
      - { label: Video Starttime, name: startTime, widget: number, required: false }
      - { label: Order About, name: order_about, widget: number, required: false }
      - { label: Order Projects, name: order_projects, widget: number, required: false }
      - { label: Order Video, name: order_video, widget: number, required: false }
      - { label: Body (DE), name: body, widget: markdown, required: false  }
      - { label: Body (EN), name: body_en, widget: markdown, required: false }
